spring.application.name=product_management

spring.datasource.url=jdbc:postgresql://localhost:5432/products_management
spring.datasource.username=postgres
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=wP9J8L1qQXK6y3sM5GZV1c4n0Q7yR2xE6gH9pA3F
app.jwt.issuer=products-management